[package]
name = "naxious/springer"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

description = "A simple Spring module, that allows you to Spring animate number | Vector2 | Vector3"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
