name: Update Naxdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
    update-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Docs Dispatch
              uses: peter-evans/repository-dispatch@v3
              with:
                token: ${GITHUB_TOKEN}
                repository: naxdocs
                event-type: update-docs
                client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
                # client-payload: '{"ref": "main"}'
